"""creators added

Revision ID: 6c34fd9c3537
Revises: 11504318a513
Create Date: 2024-12-11 23:02:00.364189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c34fd9c3537'
down_revision: Union[str, None] = '11504318a513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_t_playlists_creator_t_users'), 't_users', ['creator'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_playlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_t_playlists_creator_t_users'), type_='foreignkey')
        batch_op.drop_column('creator')

    # ### end Alembic commands ###
