"""added fk and registered_at

Revision ID: c1e60c4aeb43
Revises: dd9b3618e64e
Create Date: 2024-12-11 18:51:05.952053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e60c4aeb43'
down_revision: Union[str, None] = 'dd9b3618e64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_playlists', sa.Column('creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_playlists', 't_users', ['creator'], ['id'])
    op.add_column('t_users', sa.Column('registered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'registered_at')
    op.drop_constraint(None, 't_playlists', type_='foreignkey')
    op.drop_column('t_playlists', 'creator')
    # ### end Alembic commands ###
